### ISSUE TITLE
mapper多个文件，方法传参多个时，参数没加上@Param指定参数名报mybatis绑定错误。

### ISSUE THREAD

**Issue by jiuzheyangyo** [xaecbd/KafkaCenter#101]
![image](https://user-images.githubusercontent.com/24603363/99358749-f1d93600-28e8-11eb-8d82-a8c742721e2b.png)

**Comment by TrumanDu** [comment]
@jiuzheyangyo 可以提供详细复现步骤吗？

**Comment by jiuzheyangyo** [comment]
我是idea&nbsp;拉取源码在本地启动，然后浏览器访问，当点击左边菜单栏Monitor下的子菜单&nbsp;都会在后台报绑定错误


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "xaecbd/KafkaCenter"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年11月19日(星期四) 上午8:50
收件人:&nbsp;"xaecbd/KafkaCenter"<KafkaCenter@noreply.github.com&gt;;
抄送:&nbsp;"朱俊荣"<1058801153@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [xaecbd/KafkaCenter] mapper多个文件，方法传参多个时，参数没加上@Param指定参数名报mybatis绑定错误。 (#101)





 
@jiuzheyangyo 可以提供详细复现步骤吗？

**Comment by TrumanDu** [comment]
@jiuzheyangyo 可能你的前端代码没有编译，你启动一下前端项目，编译一下，看是否还有此类错误
