### ISSUE TITLE
Can kafkaCenter2.3 support kafka2.5/2.6

### ISSUE THREAD

**Issue by childewuque** [xaecbd/KafkaCenter#102]
I use kafka2.5 ,connect-distributed started,but  menu connect  shows "{"version":"2.5.0","commit":"66563e712b0b9f84","kafka_cluster_id":"yCJ2u5EtTAqQfeCyUjtf8w"}"  

how to fix this ?

**Comment by TrumanDu** [comment]
@childewuque Can you provide more information?
