### ISSUE TITLE
看不到图形数据

### ISSUE THREAD

**Issue by 642712364** [xaecbd/KafkaCenter#103]
![image](https://user-images.githubusercontent.com/58200037/102328535-290f3580-3fc2-11eb-86b1-417fd7f4c3a6.png)

**Comment by 642712364** [comment]
Top 10 File Size Of Topic 的折线图数据没有显示

**Comment by TrumanDu** [comment]
@642712364 kafka是否有开启jmx,已经开启收集配置

```
collect.topic.enable=true
collect.topic.period.minutes=10
```

**Comment by 642712364** [comment]
kafka是购买的云服务
