### ISSUE TITLE
monitor>Producer下无法看到图形

### ISSUE THREAD

**Issue by suishaojian** [xaecbd/KafkaCenter#104]
已经安装docker版本的kafkacenter和es，es没有做任何配置，KafkaCenter后台报错，什么原因呢？ 感谢。
![image](https://user-images.githubusercontent.com/20984440/102576540-bbcde280-4130-11eb-896b-ac2522bfd08f.png)

**Comment by TrumanDu** [comment]
@suishaojian 麻烦提供一个完整配置和es版本

**Comment by suishaojian** [comment]
# ----------------------------------------------
# MAIN APPLICATION CONFIG

# url and port where application is published
server.port=8080
public.url=http://localhost:8080

# enable/disable debug logging level
debug=false

# session timeout in seconds (21600 = 6 hours)
server.servlet.session.timeout=21600

# admin user/password to manage KafkaCenter
spring.security.user.name=admin
spring.security.user.password=admin

# url and user/password for mysql database
# if remote, make sure the user has adequate privileges (google "mysql grant privileges")
spring.datasource.url=jdbc:mysql://192.168.1.11:3306/kafka_center?useUnicode=true&characterEncoding=utf-8
spring.datasource.username=root
spring.datasource.password=123456


# ----------------------------------------------
# MONITOR

# enable/disable functionality
monitor.enable=true

# statistic collection frequency
monitor.collect.period.minutes=3

# elasticsearch config
monitor.elasticsearch.hosts=192.168.1.105:9200
monitor.elasticsearch.index=kafka_center_monitor
#monitor.elasticsearch.auth.user=
#monitor.elasticsearch.auth.password=


# ----------------------------------------------
# ALERTS

# enable/disable functionality to send consumer group lag alerts
alert.enable=false

# url of alert service (leave empty for regular internal application)
alert.service=

# default time window and threshold 
alert.dispause=2

# default threshold
alert.threshold=1000

# environment variable included in alerts
alter.env=other


# ----------------------------------------------
# EMAILS

# enable/disable functionality to trigger emails for alerts
mail.enable=false

# configuration of external mail host
spring.mail.host=
spring.mail.username=KafkaCenter@xaecbd.com
#spring.mail.password=xxxix


# ----------------------------------------------
# KAFKA CONNECT

# url where kafka connect is installed
connect.url=http://localhost:8000/#/


# ----------------------------------------------
# OAUTH2 KAFKACENTER LOGIN

# enable/disable functionality to log into application via external oauth service
generic.enabled=false

# name of service on login page
generic.name=oauth2 Login

# settings of external oauth service
generic.auth_url=
generic.token_url=
generic.redirect_utl=
generic.api_url=
generic.client_id=
generic.client_secret=
generic.scopes=


# ----------------------------------------------
# VARIOUS ADVANCED CONFIGS

# default kafka topic retention time
system.topic.ttl.h=16

# enable/disable default spring boot actuator health indicators
management.health.defaults.enabled=false

# hikari connection pool configurations 
spring.datasource.type=com.zaxxer.hikari.HikariDataSource
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.maximum-pool-size=15
spring.datasource.hikari.pool-name=KafkaCenterHikariCP
spring.datasource.hikari.max-lifetime=30000
spring.datasource.hikari.connection-test-query=SELECT 1

# mysql driver
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# enable/disable collecting list of kafka topics regularly, and set interval of collection
collect.topic.enable=true
collect.topic.period.minutes=10

# enable/disable that collection threads only collect metrics of certain cluster locations
# the location specified must be one of remote.locations below
monitor.collector.include.enable=false
monitor.collector.include.location=dev

# enable remote querying to improve lag collection behaviour, solving problems induced by latency between different locations
remote.query.enable=false
remote.hosts=gqc@localhost2:8080
remote.locations=dev,gqc


# alert group api for alert
alert.alarm.group.api=

**Comment by suishaojian** [comment]
ES版本："number" : "5.6.12"

**Comment by TrumanDu** [comment]
不支持这个es版本，请使用7.0+

**Comment by suishaojian** [comment]
> 不支持这个es版本，请使用7.0+

换了版本，图片ok了！ 感谢~

**Comment by suishaojian** [comment]
另外，请问下，是否能在query界面返回最新offset的value？

**Comment by TrumanDu** [comment]
@suishaojian 目前不支持，后续计划重写query这里的功能，会支持按时间和文本search的功能。如果项目对你有帮助，麻烦star支持一下哈。
