### ISSUE TITLE
Monitor>Lag无法显示lag，后台报错

### ISSUE THREAD

**Issue by suishaojian** [xaecbd/KafkaCenter#105]
2020-12-21 13:43:55,158 ERROR [http-nio-8080-exec-3] ElasticsearchService: getRequestBody failed!
org.elasticsearch.client.ResponseException: method [POST], host [http://192.168.1.105:9200], URI [/kafka_center_monitor*/_search], status line [HTTP/1.1 400 Bad Request]
{"error":{"root_cause":[{"type":"illegal_argument_exception","reason":"Text fields are not optimised for operations that require per-document field data like aggregations and sorting, so these operations are disabled by default. Please use a keyword field instead. Alternatively, set fielddata=true on [clusterId] in order to load field data by uninverting the inverted index. Note that this can use significant memory."},{"type":"illegal_argument_exception","reason":"Text fields are not optimised for operations that require per-document field data like aggregations and sorting, so these operations are disabled by default. Please use a keyword field instead. Alternatively, set fielddata=true on [clusterId] in order to load field data by uninverting the inverted index. Note that this can use significant memory."}],"type":"search_phase_execution_exception","reason":"all shards failed","phase":"query","grouped":true,"failed_shards":[{"shard":0,"index":"kafka_center_monitor-2020-12-20","node":"Vn3D54qdRMCgzcC4qCWIhw","reason":{"type":"illegal_argument_exception","reason":"Text fields are not optimised for operations that require per-document field data like aggregations and sorting, so these operations are disabled by default. Please use a keyword field instead. Alternatively, set fielddata=true on [clusterId] in order to load field data by uninverting the inverted index. Note that this can use significant memory."}},{"shard":0,"index":"kafka_center_monitor-2020-12-21","node":"Vn3D54qdRMCgzcC4qCWIhw","reason":{"type":"illegal_argument_exception","reason":"Text fields are not optimised for operations that require per-document field data like aggregations and sorting, so these operations are disabled by default. Please use a keyword field instead. Alternatively, set fielddata=true on [clusterId] in order to load field data by uninverting the inverted index. Note that this can use significant memory."}}],"caused_by":{"type":"illegal_argument_exception","reason":"Text fields are not optimised for operations that require per-document field data like aggregations and sorting, so these operations are disabled by default. Please use a keyword field instead. Alternatively, set fielddata=true on [clusterId] in order to load field data by uninverting the inverted index. Note that this can use significant memory.","caused_by":{"type":"illegal_argument_exception","reason":"Text fields are not optimised for operations that require per-document field data like aggregations and sorting, so these operations are disabled by default. Please use a keyword field instead. Alternatively, set fielddata=true on [clusterId] in order to load field data by uninverting the inverted index. Note that this can use significant memory."}}},"status":400}

**Comment by TrumanDu** [comment]
我猜是clusterId类型的问题，可以尝试`set fielddata=true on [clusterId] `

**Comment by TrumanDu** [comment]
不支持低于7.0的版本，文档有版本要求。
