### ISSUE TITLE
tar: config/application.properties: Cannot change ownership to uid 2000, gid 2000: Operation not permitted

### ISSUE THREAD

**Issue by yunnysunny** [xaecbd/KafkaCenter#111]
can't unzip the tar file, when I run the command `tar -zxvf KafkaCenter-Core-2.3.0-release.tar.gz`, it failed.

**Comment by TrumanDu** [comment]
@yunnysunny 权限问题，建议用sudo或者root账户再试一下

**Comment by yunnysunny** [comment]
我的是root用户

**Comment by TrumanDu** [comment]
嗯，确实
