### ISSUE TITLE
刚加入的集群topic列表为空

### ISSUE THREAD

**Issue by yunnysunny** [xaecbd/KafkaCenter#112]
我的kafka中明明有两百多个topic，但是打开topic list菜单，显示个数为零。需要等很长一段时间（大约十分钟）才出来列表内容。

**Comment by TrumanDu** [comment]
@yunnysunny topic list里面的信息是从数据库读取的，数据库里的数据是定时同步的的，因此有延迟。如果是想查看实时信息，可以在Cluster模块中查看
