### ISSUE TITLE
关闭alert了，目前报错  get virtual-email-groups has error.

### ISSUE THREAD

**Issue by childewuque** [xaecbd/KafkaCenter#113]
AlertaService: get virtual-email-groups has error.
java.lang.IllegalArgumentException: URI is not absolute

配置alert.alarm.group.api 填什么？
String response = restTemplate.getForObject(alertaConfig.getAlarmGroupApi(),String.class);

配置如下：

# ----------------------------------------------
# MAIN APPLICATION CONFIG

# url and port where application is published
server.port=8080
public.url=http://172.16.40.21:8080

# enable/disable debug logging level
debug=true

# session timeout in seconds (21600 = 6 hours)
server.servlet.session.timeout=21600

# admin user/password to manage KafkaCenter
spring.security.user.name=admin
spring.security.user.password=admin

# url and user/password for mysql database
# if remote, make sure the user has adequate privileges (google "mysql grant privileges")
spring.datasource.url=jdbc:mysql://localhost:3306/kafka_center?useUnicode=true&characterEncoding=utf-8
spring.datasource.username=root
spring.datasource.password=root

# ----------------------------------------------
# MONITOR

# enable/disable functionality
monitor.enable=true

# statistic collection frequency
monitor.collect.period.minutes=5

# elasticsearch config
monitor.elasticsearch.hosts=172.16.40.21:9200
monitor.elasticsearch.index=kafka_center_monitor
#monitor.elasticsearch.auth.user=
#monitor.elasticsearch.auth.password=

# ----------------------------------------------
# ALERTS

# enable/disable functionality to send consumer group lag alerts
alert.enable=false

# url of alert service (leave empty for regular internal application)
alert.service=

# default time window and threshold 
alert.dispause=2

# default threshold
alert.threshold=1000

# environment variable included in alerts
alter.env=jxqtest

# ----------------------------------------------
# EMAILS

# enable/disable functionality to trigger emails for alerts
mail.enable=false

# configuration of external mail host
#spring.mail.host=
#spring.mail.username=KafkaCenter@xaecbd.com
#spring.mail.password=xxxix

# ----------------------------------------------
# KAFKA CONNECT

# url where kafka connect is installed
#connect.url=http://172.16.40.22:8083/#/

# ----------------------------------------------
# OAUTH2 KAFKACENTER LOGIN

# enable/disable functionality to log into application via external oauth service
generic.enabled=false

# name of service on login page
generic.name=oauth2 Login

# settings of external oauth service
generic.auth_url=
generic.token_url=
generic.redirect_utl=
generic.api_url=
generic.client_id=
generic.client_secret=
generic.scopes=

# ----------------------------------------------
# VARIOUS ADVANCED CONFIGS

# default kafka topic retention time
system.topic.ttl.h=24

# enable/disable default spring boot actuator health indicators
management.health.defaults.enabled=false

# hikari connection pool configurations 
spring.datasource.type=com.zaxxer.hikari.HikariDataSource
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.maximum-pool-size=15
spring.datasource.hikari.pool-name=KafkaCenterHikariCP
spring.datasource.hikari.max-lifetime=30000
spring.datasource.hikari.connection-test-query=SELECT 1

# mysql driver
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# enable/disable collecting list of kafka topics regularly, and set interval of collection
collect.topic.enable=true
collect.topic.period.minutes=10

# enable/disable that collection threads only collect metrics of certain cluster locations
# the location specified must be one of remote.locations below
monitor.collector.include.enable=true
monitor.collector.include.location=test

# enable remote querying to improve lag collection behaviour, solving problems induced by latency between different locations
remote.query.enable=false
#remote.hosts=:8080
remote.locations=test

# alert group api for alert
alert.alarm.group.api=

**Comment by childewuque** [comment]
就是想监听 consume lag 等信息，展示在kafkacenter的页面上，但不想发报警通知。
好像不能支持？看了代码，monitor.enable这个是true就必然调用 alert.alarm.group.api

**Comment by TrumanDu** [comment]
@childewuque 这个我们修复一下

**Comment by TrumanDu** [comment]
仓库中最新代码已经修复
