### ISSUE TITLE
支持kafka0.8吗

### ISSUE THREAD

**Issue by TroubleJin** [xaecbd/KafkaCenter#119]

**Comment by TrumanDu** [comment]
目前是支持的

**Comment by TroubleJin** [comment]
支持接口报警吗。我看文档说明只有邮件。

**Comment by TrumanDu** [comment]
支持，aler 模块，里面可以配置webhook

**Comment by TroubleJin** [comment]
![image](https://user-images.githubusercontent.com/48788965/119453959-8c1fa800-bd6a-11eb-82e8-43f939d77412.png)
显示无法连接kafka

**Comment by TroubleJin** [comment]
![image](https://user-images.githubusercontent.com/48788965/119457407-3ea53a00-bd6e-11eb-997e-c9c7d78a1efe.png)
版本不一致问题吗
