### ISSUE TITLE
new feature

### ISSUE THREAD

**Issue by TrumanDu** [xaecbd/KafkaCenter#12]
![image](https://user-images.githubusercontent.com/16727775/78878553-29dfe700-7a85-11ea-93bf-323bbe923c65.png)

**Comment by TrumanDu** [comment]
![image](https://user-images.githubusercontent.com/16727775/78878705-657ab100-7a85-11ea-9658-17ec72ba4531.png)

**Comment by xs005** [comment]
不好意思，没搞懂怎么添加kafka的设置信息，application.properties 没有填kafka broker, schema registry, ksql server 的地方啊？

**Comment by Loernl** [comment]
https://github.com/xaecbd/KafkaCenter/blob/master/docs/UserGuide.md

**Comment by TrumanDu** [comment]
@xs005 kafka 集群信息在系统中添加，同理ksql也是。参考文档[UserGuide.md](https://github.com/xaecbd/KafkaCenter/blob/master/docs/UserGuide.md) [Module.md#ksql](https://github.com/xaecbd/KafkaCenter/blob/master/docs/Module.md#ksql)

**Comment by xs005** [comment]
找到了，谢谢！

**Comment by Y78888** [comment]
功能强大，比滴滴开源的功能强大多了，加油！！

**Comment by TrumanDu** [comment]
@Y78888 感谢，可以star支持一下我们的工作！
