### ISSUE TITLE
启动后访问8080报错，ERROR 401

### ISSUE THREAD

**Issue by Nothing2Fear** [xaecbd/KafkaCenter#127]
![微信图片_20210802203609](https://user-images.githubusercontent.com/45682547/127862915-ad47a7c5-408a-4612-a2fa-6d3449208bb1.jpg)
报错信息如图，配置文件中只修改了数据库信息

**Comment by TrumanDu** [comment]
@Nothing2Fear 没有error错误，应该是不影响使用的吧

**Comment by Nothing2Fear** [comment]
> @Nothing2Fear 没有error错误，应该是不影响使用的吧

主页都打不开，没法使用啊

**Comment by TrumanDu** [comment]
@Nothing2Fear 好的，我们验证一下。可否提供完整的操作流程

**Comment by Nothing2Fear** [comment]
> @Nothing2Fear 好的，我们验证一下。可否提供完整的操作流程

按操作拉下代码 build好jar包，然后把配置文件下载下来修改好 数据库ip密码塞回jar包里，然后启动打开主页就报401

**Comment by TrumanDu** [comment]
@Nothing2Fear 直接下载我们编译好的，再试试，配置文件不需要放到jar中，和jar放在同一个目录下，再试试。
