### ISSUE TITLE
support jdk 1.8

### ISSUE THREAD

**Issue by TrumanDu** [xaecbd/KafkaCenter#13]
目前将开发支持jdk1.8运行环境列入TODO List

**Comment by zhiyuan192shine** [comment]
请问，支持jdk8大概什么时候可以发布

**Comment by TrumanDu** [comment]
@zhiyuan192shine 预计三周。

**Comment by dosealy** [comment]
我也是西安的  找了半天找不你联系方式 能留个联系方式么 方便交流

**Comment by TrumanDu** [comment]
@dosealy 你留一下wechat,我加你！

**Comment by dosealy** [comment]
DH5331114

**Comment by TrumanDu** [comment]
代码已经修改完毕，等待测试，发布版本。着急的同学可以现在使用dev分支。

**Comment by swleon** [comment]
nice

**Comment by TrumanDu** [comment]
@zhiyuan192shine @dosealy @swleon @BeansKo 目前已经支持jdk1.8
