### ISSUE TITLE
OAuth Scopes Issues

### ISSUE THREAD

**Issue by grbesicb** [xaecbd/KafkaCenter#134]
Trying to set up Google OAuth login it seems KafkaCenter is not setting scope parameter properly.

Config value:
```
generic.scopes=https://www.googleapis.com/auth/userinfo.profile https://www.googleapis.com/auth/userinfo.email
```

Google returns:
```
Error 400: invalid_request
Missing required parameter: scope
```

**Comment by grbesicb** [comment]
> not support google OAuth

Do you plan on supporting Google OAuth any time soon?

**Comment by TrumanDu** [comment]
This non-core feature, so the open source version will not be developed
