### ISSUE TITLE
项目jar包跑起来，一点用的没有。根本运行不起来

### ISSUE THREAD

**Issue by dongjiashun** [xaecbd/KafkaCenter#139]
1.问题一，jar包配置问题，没有细节说明，就说改个数据库。然后自己看着办
2.运行的时候，jar抱起来 8080 端口，根本没法用，telnet可以通，项目上根本用不了
3.ui界面，kafka-ui项目 这个文档就一个字 谁看得懂，服了
4.安装手册没有，产品文档没有，这个星星太假了吧，内部人刷的吧

**Comment by TrumanDu** [comment]
@dongjiashun 推荐docker部署，你可以吐槽我们项目开源的不好，请不要诋毁。开源不易。

**Comment by dongjiashun** [comment]
docker也没用，jar包抱起来，  页面打开都是401。

**Comment by TrumanDu** [comment]
@dongjiashun 前端代码未编译的问题，已经修复
