### ISSUE TITLE
KafkaAdminService: validateKafkaAddress  result is inactive 添加kafka报错

### ISSUE THREAD

**Issue by haibo511** [xaecbd/KafkaCenter#16]
KafkaAdminService: validateKafkaAddress  result is inactive 添加kafka报错，怎么解决？谢谢！

**Comment by TrumanDu** [comment]
@haibo511 可以发一下你的配置参数是什么样的？

**Comment by haibo511** [comment]
xaecbd/kafka-center:2.0.1

**Comment by haibo511** [comment]
[root@localhost opt]# cat application.properties 
server.port=8080
debug=false
# 设置session timeout为6小时
server.servlet.session.timeout=21600
spring.security.user.name=admin
spring.security.user.password=admin
spring.datasource.url=jdbc:mysql://172.30.80.248:3306/kafka_center?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=zydl2019
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.type=com.zaxxer.hikari.HikariDataSource
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.maximum-pool-size=15
spring.datasource.hikari.pool-name=KafkaCenterHikariCP
spring.datasource.hikari.max-lifetime =30000
spring.datasource.hikari.connection-test-query=SELECT 1
management.health.defaults.enabled=false

public.url=http://localhost:8080
connect.url=http://localhost:8000/#/
system.topic.ttl.h=16

monitor.enable=true
monitor.collect.period.minutes=5
monitor.elasticsearch.hosts=172.30.80.249:9200
monitor.elasticsearch.index=kafka_center_monitor
#是否启用收集线程指定集群收集
monitor.collector.include.enable=false
#收集线程指定location，必须属于remote.locations之中
monitor.collector.include.location=E4
collect.topic.enable=true
collect.topic.period.minutes=10
# remote的功能是为了提高lag查询和收集，解决跨location网络延迟问题
remote.query.enable=false
remote.hosts=gqc@localhost2:8080
remote.locations=dev,gqc
#发送consumer group的lag发送给alert service
alert.enable=false
alert.dispause=2
alert.service=
alert.threshold=1000
alter.env=other
#是否开启邮件功能,true:启用，false:禁用
mail.enable=false
spring.mail.host=
spring.mail.username=KafkaCenter@xaecbd.com
# oauth2
generic.enabled=false
generic.name=oauth2 Login
generic.auth_url=
generic.token_url=
generic.redirect_utl=
generic.api_url=
generic.client_id=
generic.client_secret=
generic.scopes=

**Comment by TrumanDu** [comment]
你的kafka集群是否正常？还有它的版本，还有你新增kafka填写的参数，我分析一下

**Comment by haibo511** [comment]
CDH安装的kafka

**Comment by TrumanDu** [comment]
@haibo511 麻烦提供一下kafka版本信息，还有你新增kafka填写的参数。确保你的kafka集群是正常的

**Comment by haibo511** [comment]
2.2.1+kafka4.1.0
--

**Comment by haibo511** [comment]
ip:9092

**Comment by haibo511** [comment]
2.4.1.0.p0.6
--

**Comment by TrumanDu** [comment]
目前看不出更有效信息，出错的原因可能是

1.  部署KafkaCenter机器无法连接kafka集群
2.  ip:9092填写错误
3. 连接超时，检查一下kafka本身集群健康状况

**Comment by haibo511** [comment]
192.168.1.29:9092，这样写对吗？
