### ISSUE TITLE
【elasticsearch用户名和密码认证支持】

### ISSUE THREAD

**Issue by xfirefox** [xaecbd/KafkaCenter#18]
目前使用elasticsearch版本7.6.1，配置了用户名和密码认证。期望KafkaCenter支持。

**Comment by tithonus163** [comment]
不要仅支持7.x,  
6.x也要支持一下.
同样都是认证的.

**Comment by TrumanDu** [comment]
@xfirefox 已经在dev库支持用户名和密码认证。
@tithonus163 由于监控图聚合使用了自动聚合，这个功能只在7.x支持。所以暂时不支持6.x版本。

**Comment by masato-xd** [comment]
@TrumanDu dev库添加的es用户密码功能，是不是通过docker方式启动也不会生效？要mvn打包启动的方式吗。

**Comment by TrumanDu** [comment]
@masato-xd 是的，dev还没合并到master，未来一个月会发布新版本，发布新版本，docker才会支持。目前只能自己build源码

**Comment by TrumanDu** [comment]
master已经支持该功能！
