### ISSUE TITLE
请问使用Kafka connect功能还需要单独安装kafka-connect-ui吗？

### ISSUE THREAD

**Issue by 1411643015** [xaecbd/KafkaCenter#21]
在知乎上了解到了我们这个项目，很看好项目中的connect管理功能，今天clone了一份KafkaCenter代码到我的IDEA里面可以运行起来，但是Kafka connect界面是空白的，请问这个功能的使用时需要单独再安装kafka-connect-ui吗？（我只是在IDEA里面启动了一下项目，然后UI上面看下功能，并没有对Kafka进行配置，不知道是不是这个原因导致Kafka connect界面空白），附截图：
![TIM图片20200420181956](https://user-images.githubusercontent.com/35264598/79741288-92577f80-8333-11ea-8087-8cc770c564bd.png)
最后，非常感谢大佬们提供的项目！

**Comment by TrumanDu** [comment]
@1411643015 connect需要另外单独部署，可以参考[文档](https://github.com/xaecbd/KafkaCenter/blob/master/docs/KafkaConnectUi.md)
