### ISSUE TITLE
API 怎么访问?

### ISSUE THREAD

**Issue by tithonus163** [xaecbd/KafkaCenter#38]
如 kafka-manager 自带的API:
curl -s -XGET 'http://admin:admin@127.0.0.1:80/api/status/clusters'

GET    /api/status/:c/brokers                               controllers.api.KafkaStateCheck.brokers(c:String)
GET    /api/status/:c/brokers/extended                      controllers.api.KafkaStateCheck.brokersExtended(c:String)
GET    /api/status/:c/topics                                controllers.api.KafkaStateCheck.topics(c:String)
GET    /api/status/:c/topicIdentities                       controllers.api.KafkaStateCheck.topicIdentities(c:String)
GET    /api/status/clusters                                 controllers.api.KafkaStateCheck.clusters
GET    /api/status/:c/:t/underReplicatedPartitions          controllers.api.KafkaStateCheck.underReplicatedPartitions(c:String,t:String)
GET    /api/status/:c/:t/unavailablePartitions              controllers.api.KafkaStateCheck.unavailablePartitions(c:String,t:String)
GET    /api/status/:cluster/:consumer/:topic/:consumerType/topicSummary   controllers.api.KafkaStateCheck.topicSummaryAction(cluster:String, consumer:String, topic:String, consumerType:String)
GET    /api/status/:cluster/:consumer/:consumerType/groupSummary          controllers.api.KafkaStateCheck.groupSummaryAction(cluster:String, consumer:String, consumerType:String)
GET    /api/status/:cluster/consumersSummary                controllers.api.KafkaStateCheck.consumersSummaryAction(cluster:String)

**Comment by TrumanDu** [comment]
@tithonus163 该api未开放，可以自由行修改拦截器实现
