### ISSUE TITLE
Missing English Translations / Improvable English Translations

### ISSUE THREAD

**Issue by matthiaspfenninger** [xaecbd/KafkaCenter#46]
#### There are missing English translations in the UI in several places:
1. *please choose role* label for drop down in Setting --> User --> Add User: Role
2. *please choose location* for drop down in Kafka Manager --> Cluster --> Add New Cluster: Location
3. *Items Per Page* label at bottom of tables (all tables affected)
4. *Previous* and *Next* at bottom of tables (all tables affected)
5. *No Data* label for empty tables (all empty tables affected)
6.  *No Options* if clicking on dropdowns without any options (all dropdowns affected, e.g. Monitor --> Alert --> Create Alert: Topic Name)

#### There are some translations which are improvable:
1. Kafka Manager --> Cluster --> Add New Cluster: *Advance* should be **Advanced**
2. Kafka Manager --> Cluster --> Add New Cluster:  *ClusterName* should be **Cluster Name**
3. Monitor --> Alert --> Create Alert: *Diapause* is only used in context with animals. What is meant here? Maybe **Time Window** in which threshold has to be reached?
4. Monitor --> Alert --> Create Alert: *DisableAlerta* should probably be **Disable Alerts**
5. *My Favorite* is usually not used in singular, I would change it to **Favorites**
6. *Setting* is usually not used in singular, I would change it to **Settings**
7. *My Task* is singular but should be plural **My Tasks*

### Versions
2.1.0 (reproducible with Docker image `xaecbd/kafka-center:2.1.0`)

#### Missing Translations
1. 
![image](https://user-images.githubusercontent.com/38106012/81965387-4806ad00-9618-11ea-8685-23692542cf96.png)

2. 
![image](https://user-images.githubusercontent.com/38106012/81965457-5c4aaa00-9618-11ea-8dac-480a6d0953ce.png)

3. 
![image](https://user-images.githubusercontent.com/38106012/81965528-75535b00-9618-11ea-8295-e75b1fb224d6.png)

4. 
![image](https://user-images.githubusercontent.com/38106012/81965698-b9def680-9618-11ea-94c5-ec1f134431f8.png)

5. 
![image](https://user-images.githubusercontent.com/38106012/81965514-6ec4e380-9618-11ea-94fd-cf25bb94b10c.png)

6. 
![image](https://user-images.githubusercontent.com/38106012/81965778-d844f200-9618-11ea-985c-8e8353fd4cc6.png)

#### Improvable Translations
1. / 2. 
![image](https://user-images.githubusercontent.com/38106012/81965837-eabf2b80-9618-11ea-8109-8b1c7e32af91.png)

3. / 4. 
![image](https://user-images.githubusercontent.com/38106012/81965897-01658280-9619-11ea-8c60-f33ac2b17e3b.png)

5. / 6. / 7. 
![image](https://user-images.githubusercontent.com/38106012/81965882-f9a5de00-9618-11ea-8900-1937c2468616.png)

**Comment by TrumanDu** [comment]
@matthiaspfenninger thanks for u reply.we will fix it.

**Comment by TrumanDu** [comment]
now ,fix it.
