### ISSUE TITLE
Improve English Documentation

### ISSUE THREAD

**Issue by matthiaspfenninger** [xaecbd/KafkaCenter#47]
The feature set of Kafka Center really looks promising so far. In order advance more quickly it would be great to enable non-Chinese developers to participate more easily. 

I suggest to improve the English documentation in several places:
- Improve main README spelling and formulation 
- Add English contributing guidelines
- Have a version of *application.properties* that is clean in English with improved comments
- Promote writing issues and PRs in English by adding templates

Optionally also:
- Change titles of existing issues to English
- Translate other guides (user guide, admin guide) to English

I'm happy to help on this via a PR if you agree.

**Comment by TrumanDu** [comment]
@matthiaspfenninger yeah，we need you. Looking forward to your contribution.
