### ISSUE TITLE
是否有kafkacenter的QQ交流群或微信群呢？建议组织个交流群

### ISSUE THREAD

**Issue by dusansheng** [xaecbd/KafkaCenter#52]

**Comment by l4dfire** [comment]
不推荐拉群，好好维护github就行。 
不然同样的内容要维护在两个地方，并且群聊记录不能索引存在大量重复问题的可能，群不精心维护就容易崩成灌水区， 反而让新进群的coder印象不好。

**Comment by TrumanDu** [comment]
还是建议在issue提交问题，我们基本会当天回复。
