### ISSUE TITLE
[Bug]Is KafkaCenter requied  specified version of mysql?

### ISSUE THREAD

**Issue by wangyunpeng666** [xaecbd/KafkaCenter#55]
application.properties has been configured correctly,Once  WHEN I started kafkaCenter,it met errors.
![image](https://user-images.githubusercontent.com/57751906/82400940-1152eb80-9a8b-11ea-94e1-b8a94c907845.png)
![image](https://user-images.githubusercontent.com/57751906/82400984-2760ac00-9a8b-11ea-9c0a-164c5d8b28ee.png)
 The version of mysql is 5.1.73,Could you give me some help?

**Comment by TrumanDu** [comment]
@wangyunpeng666 
可以试试如下命令，搭建一个mariadb
```
docker run --name mariadb -e MYSQL_ROOT_PASSWORD=123456 -p 3306:3306 -d mariadb:10.5.2
```


```
spring.datasource.url=jdbc:mysql://127.0.0.1:3306/kafka_center
```

或者：

更改mysql驱动版本
```
<dependency>
            <groupId>mysql</groupId>
            <artifactId>mysql-connector-java</artifactId>
            <version>xxx</version>
        </dependency>
```

或者尝试：

```
spring.datasource.url=jdbc:mysql://127.0.0.1:3306/kafka_center?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
```

**Comment by wangyunpeng666** [comment]
试了后两种方法都不可行，第一种方法可行，多谢了！
