### ISSUE TITLE
希望能支持JDK8

### ISSUE THREAD

**Issue by afish177** [xaecbd/KafkaCenter#58]
希望能支持JDK8

**Comment by TrumanDu** [comment]
@afish177 已经支持jdk1.8，请查看最新版本和文档

**Comment by afish177** [comment]
好的 谢谢大佬




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"truman.p.du"<notifications@github.com&gt;;
发送时间:&nbsp;2020年5月26日(星期二) 晚上9:27
收件人:&nbsp;"xaecbd/KafkaCenter"<KafkaCenter@noreply.github.com&gt;;
抄送:&nbsp;"浮生ふ物语"<372049596@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [xaecbd/KafkaCenter] 希望能支持JDK8 (#58)





 
@afish177 已经支持jdk1.8，请查看最新版本和文档
