### ISSUE TITLE
Config via UI

### ISSUE THREAD

**Issue by b0bai** [xaecbd/KafkaCenter#6]
Hi, 

Great application, I do hope to contribute it when I can.

It'd be great to have an initial UI that can be used to configure the application, instead of doing it manually via the `application.properties` files and of course, that includes the execution of the SQL script as well.

**Comment by TrumanDu** [comment]
@b0bai  yeah.That's better.But I want to make more useful functions.

**Comment by TrumanDu** [comment]
@b0bai  yeah.that's better.But I want to make more useful functions
