### ISSUE TITLE
KafkaConsumerServer.java 中的 getLogSize() 使用subscribe()  会产生Consumer Rebalance

### ISSUE THREAD

**Issue by xinzhuxiansheng** [xaecbd/KafkaCenter#65]
Master分支：
KafkaConsumer<String, String> kafkaConsumer = consumer.subscribe(topicName);
调用
public KafkaConsumer<K, V> subscribe(String toppicName) {
		this.consumer.subscribe(Collections.singleton(toppicName));
		return this.consumer;
	}

这个会引起其他当前groupid下的members Consumer 进行Rebalance，这样做不合理。

你可以在 KafkaConsumer实例化后，直接调用partitionsFor(topicName)，拿到Metadata的EndOffset , committedOffset

**Comment by TrumanDu** [comment]
@xinzhuxiansheng 感谢你的建议，我这边review后，调整一下

**Comment by TrumanDu** [comment]
@xinzhuxiansheng 已经验证，并修复，后续会合并代码！
