### ISSUE TITLE
Kafka-Center连接Kafka失败

### ISSUE THREAD

**Issue by iamyangzehao** [xaecbd/KafkaCenter#67]
安装完Kafka-Center之后，进入到Connect页面，显示localhost 拒绝了我们的连接请求。我的kafka和Kafka-Center安装在同一台机器上，connect.url=http://localhost:8000/#/，难道这里配置localhost不行吗？需要配置具体的ip？

**Comment by TrumanDu** [comment]
@iamyangzehao 这个需要配置成connect主机ip的
