### ISSUE TITLE
使用dev库，本地编译运行，配置带认证的ME

### ISSUE THREAD

**Issue by masato-xd** [xaecbd/KafkaCenter#68]
![image](https://user-images.githubusercontent.com/22469964/85495373-f6851100-b60c-11ea-9929-5478ef7da8fe.png)

使用的是dev库的版本，配置了es7的密码认证参数，然后点击monitor-----Lag的时候报错
请问一下，这个错误是因为什么原因。？有解决办法吗。

**Comment by TrumanDu** [comment]
@masato-xd 可能是你配置的es有问题，麻烦贴一下其他error log和你的配置文件

**Comment by masato-xd** [comment]
还需要其他日志吗？
![image](https://user-images.githubusercontent.com/22469964/85935383-c5fde980-b922-11ea-844d-accdc06544cb.png)
![image](https://user-images.githubusercontent.com/22469964/85935388-d2824200-b922-11ea-885b-685f7a7bc48c.png)
![image](https://user-images.githubusercontent.com/22469964/85935393-d910b980-b922-11ea-96ec-56baffae5161.png)
![image](https://user-images.githubusercontent.com/22469964/85935395-df069a80-b922-11ea-96d4-6875785d6df0.png)

配置文件如下：
![image](https://user-images.githubusercontent.com/22469964/85935410-15441a00-b923-11ea-9cd1-02e627782222.png)


麻烦了~~

**Comment by TrumanDu** [comment]
@masato-xd 我这边验证一下，应该是bug

**Comment by TrumanDu** [comment]
@masato-xd 已经验证，该问题是因为你的es无数据，造成拉数据报错，属于bug ，感谢回馈！

**Comment by TrumanDu** [comment]
@masato-xd 已经fix,修复后代码在dev分支
