### ISSUE TITLE
部门信息有接口对接公司的组织架构吗?

### ISSUE THREAD

**Issue by nondevops** [xaecbd/KafkaCenter#7]
部门信息有接口对接公司的组织架构吗?

**Comment by TrumanDu** [comment]
支持oauth2登录，可在配置文件配置。不支持导入组织，需要手动创建team，再将用户导入到team中。用户数据只要登录系统，就会导入进来。

**Comment by Loernl** [comment]
可以后续支持excel导入数据库么

**Comment by TrumanDu** [comment]
@Loernl 我个人觉得没必要
