### ISSUE TITLE
求助 mysql 连接不上~~The driver has not received any packets from the server

### ISSUE THREAD

**Issue by lizeyun** [xaecbd/KafkaCenter#72]
kafka_center docker 版本：xaecbd/kafka-center:2.1.0
maridb docker 版本： 
![image](https://user-images.githubusercontent.com/19726385/86918965-07c83480-c15a-11ea-927e-b77c617e17b9.png)

报错截图：
![image](https://user-images.githubusercontent.com/19726385/86919004-19a9d780-c15a-11ea-9047-c52bd44ee204.png)

jdbc 配置截图：
![image](https://user-images.githubusercontent.com/19726385/86919062-31815b80-c15a-11ea-8a9e-01bf2c31bea1.png)

**Comment by lizeyun** [comment]
参考了其他issue ，本地起了一个mariadb, 结果还是不行

**Comment by TrumanDu** [comment]
@lizeyun 你的mysql可以用客户端访问吗？还有你的具体过程可以描述一下吗？比如机器是否存在多网卡等。程序是否是使用docker启动？可否先尝试全部用docker 部署。目前的log我无法确实能够是哪里的问题。

**Comment by TrumanDu** [comment]
@lizeyun 我先关闭该issue,如果你还有问题，再重新打开。

**Comment by trumpisasb** [comment]
这个问题吧，我说下我解决的步骤。
开始也是报错，mysql连接不上。其实原因是配置文件里面要配置下使用ip或者其他方式连接。 初始是用localhost来的。docker里面有没有localhost的mysql，所以肯定错误。 
步骤1. 先安装一个mysql或者mariadb，docker或者自有mysql，启动即可。
步骤2.修改配置文件，将mysql改为步骤1中启动mysql的ip地址。（确保步骤1中的mysql可以外部连接）
步骤3.启动docker。应该就可以了。

建议作者 @TrumanDu  来一份docker-compose吧，这样properties中mysql直接用，，不然我看问题中大都是mysql连接不上的。。或者给一份说明。
