### ISSUE TITLE
虚拟机启动如何指定配置文件?

### ISSUE THREAD

**Issue by nondevops** [xaecbd/KafkaCenter#8]
虚拟机启动如何指定配置文件?

**Comment by TrumanDu** [comment]
@nondevops 你是说java虚拟机，还是？？？

**Comment by Hulva** [comment]
下载[配置文件](https://raw.githubusercontent.com/xaecbd/KafkaCenter/master/KafkaCenter-Core/src/main/resources/application.properties)，把Mysql，ElasticSearch（可选）替换成你自己的环境，然后在你编辑好的配置文件的目录下执行一下命令就好了
```
docker run -d -p 8080:8080 --name KafkaCenter -v ${PWD}/application.properties:/opt/app/kafka-center/config/application.properties xaecbd/kafka-center:2.0.1
```
REAMDME 文档 Getting Started 部分有说明

**Comment by nondevops** [comment]
> @nondevops 你是说java虚拟机，还是？？？

用openstack孵化的虚拟机,如何在非doccker环境直接启动虚拟机?我看到docker启动的时候是指定了配置文件的,不知道虚拟机启动的时候怎么指定配置文件

**Comment by TrumanDu** [comment]
@nondevops 没用过。你们是如何部署java应用的？可以在jar所在目录新建文件夹`config`，然后将配置文件放置在该目录下。你们虚拟机应该是支持外挂文件的吧。
