### ISSUE TITLE
监控图怎么做呢

### ISSUE THREAD

**Issue by wakerwang** [xaecbd/KafkaCenter#84]

**Comment by TrumanDu** [comment]
@wakerwang 什么意思？

**Comment by wakerwang** [comment]
就是和ES集成的时候，资料太少了

**Comment by wakerwang** [comment]
@TrumanDu 就是和ES集成的时候，资料太少了

**Comment by TrumanDu** [comment]
@wakerwang 只用在配置文件中配置ip和index就好了，其他都是自动的。

**Comment by wakerwang** [comment]
@TrumanDu  能把具体的参数名字贴出来吗？我没找到

**Comment by TrumanDu** [comment]
```
# elasticsearch config
monitor.elasticsearch.hosts=localhost:9200
monitor.elasticsearch.index=kafka_center_monitor
#monitor.elasticsearch.auth.user=
#monitor.elasticsearch.auth.password=
```

https://github.com/xaecbd/KafkaCenter/blob/master/KafkaCenter-Core/src/main/resources/application.properties

**Comment by wakerwang** [comment]
![image](https://user-images.githubusercontent.com/34649728/93745490-3799bb00-fc26-11ea-971e-d84dcee11568.png)

配的一样，就是这个图出不来

**Comment by wakerwang** [comment]
@TrumanDu 
![image](https://user-images.githubusercontent.com/34649728/93745544-5009d580-fc26-11ea-8a2d-e9a557b8331a.png)
配的一样，就是这个图出不来
