### ISSUE TITLE
JmxCollector类中在计算metrics 尽量用多线程吧

### ISSUE THREAD

**Issue by xinzhuxiansheng** [xaecbd/KafkaCenter#95]
在JmxCollector.metricEveryBrokerTopic() 方法，在计算各个mbean Name的metrics 建议还是使用多线程吧
for (String metric : metricName) {
	MeterMetric meterMetric = getMetricValue(metric, topic, jmxConnector.getMBeanServerConnection());
	meterMetric.setMetricName(metric);
	meterMetric.setBroker(brokerInfo.getHost());
	meterMetric.setJmxPort(String.valueOf(brokerInfo.getJmxPort()));
	meterMetric.setPort(String.valueOf(brokerInfo.getPort()));
	metricSet.add(meterMetric);
}
明确表示，这不是BUG，不过可以当做MINOR，至少也是好的开发习惯

**Comment by TrumanDu** [comment]
@xinzhuxiansheng 用线程无非考虑的速度更快，这里没用线程是基于我们的的场景，计算后时间是可接受的。KafkaCenter内部大量创建的线程，为了避免滥用多线程，我们会在可接受的性能的前提下，控制线程的数量。

感谢你的建议

**Comment by xinzhuxiansheng** [comment]
好的,  的确很感叹 yahoo/CMAK 的项目的模式 akka+scala， 这也确实是个好的架构的实现方式， :)
