### ISSUE TITLE
建议引入代码格式检查并格式化现有代码

### ISSUE THREAD

**Issue by dengliming** [xaecbd/KafkaCenter#96]
我个人感觉代码格式比较混乱很影响可读性

**Comment by TrumanDu** [comment]
@dengliming 有业界主流和推荐方案吗？

**Comment by dengliming** [comment]
可以用maven的这个插件`maven-checkstyle-plugin`

**Comment by dengliming** [comment]
@TrumanDu 觉得这个提议怎么样，如果可以我这边可以提个pr

**Comment by TrumanDu** [comment]
@dengliming 不反对这个，你可以先提，我们看一下效果
