### ISSUE TITLE
想要配置context-path，前后端改怎么改？

### ISSUE THREAD

**Issue by helloyaoge** [xaecbd/KafkaCenter#97]
想通过nginx 做反向代理。

**Comment by TrumanDu** [comment]
@helloyaoge 
```
    server {
        listen       80;
        server_name  localhost;

        location / {
			proxy_pass http://127.0.0.1:8866;
			proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
		}
		error_page 404 /404.html;
            location = /40x.html {
        }
        error_page 500 502 503 504 /50x.html;
            location = /50x.html {
        }
    }

```

**Comment by helloyaoge** [comment]
我这个nginx 上面有多个服务，必须要有个前缀，比如  localhost /kafkaCenter{

}
然后，springboot的 工程的前后端配置了contextt-path。前端配置请求。但是，springboot 加载不到静态资源

**Comment by TrumanDu** [comment]
没理解你的问题

**Comment by helloyaoge** [comment]
比如后端的地址是： /home/queryPage ，配置了server.servlet.context-path =kafkaCenter 之后。 后端的接口的实际地址变成了。/kafkaCenter/home/queryPage/。 前端配置了 axiosInstance.defaults.baseURL ='/kafkaCenter。 然后前端重新打包到static下面，就报找不到css,js 这种资源问题。 我的那个nginx 上面有很多服务。所有是kafkaCenter的前缀，我会认为是这个kafka的监控服务。就是相当于在原来的请求路径上加一个固定的前缀。 用来做nginx的反向代理

**Comment by TrumanDu** [comment]
@helloyaoge  可以考虑前后端分离，修改前端编译目录，用ng做容器，代理前端服务就好了

**Comment by helloyaoge** [comment]
能在某个分支上支持一个版本吗？ 我对这个ng和前端不是很熟悉

**Comment by helloyaoge** [comment]
![image](https://user-images.githubusercontent.com/12529019/99142566-2d79c300-2691-11eb-90ca-7fd4e7fca52f.png)


直接放到nginx下面就这个样子了，是不是打包的路径不对
