### ISSUE TITLE
配置文件alert.alarm.group.api

### ISSUE THREAD

**Issue by bfc-maple** [xaecbd/KafkaCenter#98]
配置文件
#alert group api for alert
alert.alarm.group.api=
什么意思?要填什么?
String response = restTemplate.getForObject(alertaConfig.getAlarmGroupApi(),String.class);
会报错

**Comment by TrumanDu** [comment]
@bfc-maple 忽略这个配置，这个是给alerta的一个配置，你们应该无用！
